# Generated by Django 5.1.2 on 2024-11-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recorder",
            name="age",
        ),
        migrations.RemoveField(
            model_name="recorder",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="MainVoiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mv_json", models.JSONField()),
                (
                    "parentModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recorder.recorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MangaImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parentModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recorder.recorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleVoiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sv_json", models.JSONField()),
                (
                    "parentModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recorder.recorder",
                    ),
                ),
            ],
        ),
    ]
