# Generated by Django 5.1.2 on 2024-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorder", "0003_mastermodel_remove_mangaimagemodel_parentmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mastermodel",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="mastermodel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="mastermodel",
            name="mv_json",
        ),
        migrations.RemoveField(
            model_name="mastermodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="mastermodel",
            name="order",
        ),
        migrations.RemoveField(
            model_name="mastermodel",
            name="sv_json",
        ),
        migrations.AlterField(
            model_name="mastermodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
