# Generated by Django 5.1.2 on 2024-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recorder",
            "0004_remove_mastermodel_comment_remove_mastermodel_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mastermodel",
            name="manga_json",
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name="mastermodel",
            name="mv_json",
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name="mastermodel",
            name="sv_json",
            field=models.TextField(default=dict),
        ),
        migrations.AlterField(
            model_name="mastermodel",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
