# Generated by Django 5.1.2 on 2024-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorder", "0005_mastermodel_manga_json_mastermodel_mv_json_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastermodel",
            name="mv_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="mastermodel",
            name="sv_json",
            field=models.JSONField(default=dict),
        ),
    ]
