# Generated by Django 5.1.2 on 2024-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorder", "0006_alter_mastermodel_mv_json_alter_mastermodel_sv_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastermodel",
            name="manga_json",
            field=models.JSONField(default=list),
        ),
    ]
